name: Windows CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: download authproxy
        run: Invoke-WebRequest -Uri "https://dl.duosecurity.com/duoauthproxy-latest.exe" -OutFile "duoauthproxy-lastest.exe"
      - name: Instlal authproxy
        run: .\duoauthproxy-lastest.exe /S /exclude-auth-proxy-manager
      - name: Copy Config
        run:  Copy-Item .\authproxy.cfg "C:\Program Files\Duo Security Authentication Proxy\conf\"
      - name: restart authproxy
        run: Start-Process "C:\Program Files\Duo Security Authentication Proxy\bin\authproxyctl.exe" restart
      - name: restart authproxy
        run: Start-Process "C:\Program Files\Duo Security Authentication Proxy\bin\authproxy_support.exe"
      - name: Archive support tool result
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: "C:/Program Files/Duo Security Authentication Proxy/duoauthproxy-support-*.zip"